const enum ACTIONS {
  CREATE_FILE = 'CREATE_FILE',
  CREATE_DIRECTORY = 'CREATE_DIRECTORY',
  RENAME = 'RENAME',
  DELETE = 'DELETE',
  OPEN_WISH_LIVE_SERVER = 'OPEN_WISH_LIVE_SERVER',
}

export default ACTIONS;
